; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-d1-mini]
platform = espressif32
board = esp32dev  ; Bleibt gleich, ESP32 D1 Mini nutzt dieselbe Basis
framework = arduino
lib_deps = 
  xreef/EByte LoRa E220 library@^1.0.8
  sstaub/TickTwo@^4.4.0
  knolleary/PubSubClient@^2.8.0
 

upload_speed = 921600
monitor_speed = 115200

